name: Delete All Workflow Runs

on:
  schedule:
    - cron: "0 0 1 * *" # Run monthly at midnight on the 1st day of the month
  workflow_dispatch: # Allow manual triggering

jobs:
  delete_all_workflows:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get all workflows
        id: workflows
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows" \
            | jq '.workflows[] | {id: .id, name: .name}' > workflows.json
          echo "Workflows fetched: $(cat workflows.json)"

      - name: Delete old workflow runs
        env:
          REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Read workflows from the JSON file
          workflows=$(jq -r '.[] | .id' workflows.json)

          # Loop through each workflow
          for workflow_id in $workflows; do
            echo "Processing workflow ID: $workflow_id"

            # Get workflow runs older than 10 days
            runs=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$REPO/actions/workflows/$workflow_id/runs?per_page=100&status=completed" \
              | jq -r --arg date "$(date -d '10 days ago' --iso-8601=seconds)" \
                '.workflow_runs[] | select(.created_at < $date) | .id')

            # Delete each run
            for run_id in $runs; do
              echo "Deleting workflow run ID: $run_id"
              curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/$REPO/actions/runs/$run_id"
            done
          done
